dist: xenial
sudo: required
language: node_js
node_js:
    - 'node'
    - '14.6.0' # Main version used by HTK server
    - '12.16' # Pinned, because node's H2 is buggy in 12.17+
    - '10'
install:
    - npm install --no-package-lock
services:
    - xvfb
before_script:
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
    - npm run ci
after_success:
    - touch ./typedoc/.nojekyll # Ensure doc files starting with _ get published
addons:
    chrome: stable
jobs:
    include:
        - stage: Deploy Docs
          deploy:
            provider: pages
            skip-cleanup: true
            local-dir: typedoc
            github-token: $GITHUB_TOKEN
            on:
                branch: master
