dist: xenial
sudo: required
language: node_js
node_js:
    - 'node'
    - '12'
    - '10'
    - '8'
install:
    - npm install --global npm@4
    - npm install
services:
    - xvfb
before_script:
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
    - npm run ci
addons:
    chrome: stable
jobs:
    include:
        - stage: Deploy Docs 
          deploy:
            provider: pages
            skip-cleanup: true
            local-dir: typedoc
            github-token: $GITHUB_TOKEN
            on:
                branch: master
